### ISSUE TITLE
Checksum mismatch

### ISSUE THREAD

**Issue by vinyldarkscratch** [tintinplusplus/tintin#4]
As described in https://github.com/Homebrew/homebrew-core/issues/22563, the checksum for release 2.01.4 doesn't match.  Looking at the commit history, however, a strange thing was that the commit was placed on the 6th, while the release was on the 7th (in my time zone).  My guess is it was a bad auto-update, but I just want to confirm?

**Comment by avidal** [comment]
Unfortunately, this is an unofficial (and apparently outdated) mirror of the official releases. At one point I was actively pulling the release tarballs, unpacking them, and pushing them here to have some semblance of commit history.

If the official release of 2.01.4 has a mismatched checksum there's unfortunately nothing I can do about it.

**Comment by avidal** [comment]
For what it's worth, I did upload the last several releases (including 2.01.4), but again I can't do anything about the checksum mismatch on Sourceforge.

**Comment by avidal** [comment]
Ah, just saw homebrew/homebrew-core#22672 with Scandum's reply on what happened with the checksum. Thanks for reaching out.
