### ISSUE TITLE
Unicode characters counted incorrectly for line length

### ISSUE THREAD

**Issue by KazDragon** [tintinplusplus/tintin#5]
Hey Scandum.

The error seems to be that, when calculating whether or not to move to the next line, Unicode characters are counted per byte rather than per character.

The effect of this is if I, for example, use character U+25F4 (white circle with upper left quadrant) repeatedly, then I get roughtly a third of the way across the screen before it starts printing on the next line.

There's a bit of an overlap when using values 0x80-0xFF vs. Unicode characters, but we have a way out:  ESC % G / ESC % @ can be used to shift in and out of a UTF-8 character set (see my favourite source http://invisible-island.net/xterm/ctlseqs/ctlseqs.html).  This is reasonably portable across terminals.

Also, the register button on your Sourceforge forums is broken, or I'd mention this there.  And so is MudBytes' password reset -.-

**Comment by avidal** [comment]
I have no clue if Scandum actually looks at anything here or not, I just mirror the releases manually when I notice a new one comes out. I went ahead and posted it on the forums though on your behalf: http://tintin.sourceforge.net/board/viewtopic.php?p=10169

**Comment by KazDragon** [comment]
Thanks, Avidal.  Much appreciated.

**Comment by avidal** [comment]
Scandum says:

> Thanks, he probably forgot to use: #config charset UTF-8 
The beta release tries to figure out the charset automatically. 
I still have to make time to look into the registration issue.

Closing this now; once the beta is fully released I'll update the repository.
