### ISSUE TITLE
dual license

### ISSUE THREAD

**Issue by communityus** [tintinplusplus/tintin#6]
I understand this is an unofficial group. However I assume you and yours have posted some on the tintin forum: https://tintin.sourceforge.io/forum

Question is, can we make it official on this unofficial group that tintin was always public domain dual licensed. I find in several places both wintin and on tintin forums that Scandum started with the code in public domain and slapped a GPLv2 license on it (likely because it was was hot then) I also gather Scandum has seen codebases like bitcoin going MIT, maybe we can make it official with permission that the tintinplusplus group's github code is licensed MIT with Scandum permission of course. Or something less restrictive.

The issue is well summarized by if we find a library that is closed source, we can find another library that does the same thing in GPL, if we MIT the library to begin with we can stop rewriting libraries.

Since this group has some ins with tintin already, I assumed post here and see if you might take the thought to Scandum. At a min. level the ask is ... if we can't officially be public domain or MIT here can we at least allow the simple exception of letting others learn from the GPL code and make derivative work that is still open source source even if non-gpl open source.

Ref: (below are convo's I found on the matter, in one code is offered in public domain not gpl and Scandum has no issue, in another we see tintin is dual licensed in Scandums' mind already - just not for everyone else [which is their right of course - just hoping we can make it official we are dual licensed now - its time]  and last Scandum suggest for user contributed code to be public domain, but reader didn't understand GPL is not public domain as Scandum wanted to have the option to not GPL code and scripts used at a later time)

License: https://tintin.sourceforge.io/forum/viewtopic.php?f=2&t=1991&p=7826&hilit=public+domain#p7826 I'm not going to license it, it's public domain stuff. I don't care what you do or don't do with it, and I don't believe that simply calling the tt++ binary requires me to make it GPL. If I'm wrong, please correct me.

Post by Scandum » Sat Aug 10, 2013 5:51 pm Cool stuff. I've linked it from the webpage, feel free to backlink.

https://tintin.sourceforge.io/forum/viewtopic.php?f=2&t=1991&p=7826&hilit=public+domain#p7826 Last but not least, ytin is GPL, while tintin is licensed under GPL I could change that if I wanted to, which I could no longer if I start adding code from GPLed programs. So I want to either add all new code from scratch or use public domain code.

https://tintin.sourceforge.io/forum/viewtopic.php?f=7&t=2559&p=10381&hilit=license#p10381 While I release TinTin++ as GPL 2 the sourcecode I started out with was public domain, and I'd like to be able to re-license the software without needing anyone's permission. :)

**Comment by avidal** [comment]
I'm not sure if most/any of us are still active users or posters on the forums. Originally, I created this mirror on my own github account and only shifted it to @tintinplusplus after it was created.

I periodically check the forums for new releases and synchronize here. I think if you want clarity on the license you should post to the forums and ask for clarity.

**Comment by scandum** [comment]
All my previous tintin++ releases are strictly licensed under GPL 2, and as of version 2.01.8 all releases will be licensed under GPL 3.

Since I don't encourage code contributions and 99% of the code is written by me I make it clear that if anyone submits a patch they have to release their patch into the public domain so I don't end up having to ask anyone's permission to do with my 99% as I please.

My choice for GPL was not a spur of the moment thing, I'm a strong believer in free software and under no circumstances is the software to be released under an MIT license.

**Comment by communityus** [comment]
Thanks for clarifying. It also looks like you went through creating a GitHub account just to do so, so twice thanks.
